spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service/api/user
          predicates:
            - Path=/api/user/{segment}
        - id: auth-service-route
          uri: lb://auth-service/api/user
          predicates:
            - Path=/api/auth/{segment}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



